// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGZ_JRCAidAZVsnsvRwQcNWwasGNYVAnA',
    appId: '1:985173152011:web:c5cce3b3c8d985eb25120e',
    messagingSenderId: '985173152011',
    projectId: 'inventory-app-siyam',
    authDomain: 'inventory-app-siyam.firebaseapp.com',
    storageBucket: 'inventory-app-siyam.firebasestorage.app',
    measurementId: 'G-PWHHJBX83J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqQTR0Mmw8U5HSaUi0HJxNEKkV5yXtU6o',
    appId: '1:985173152011:android:e1e5133f30b1654725120e',
    messagingSenderId: '985173152011',
    projectId: 'inventory-app-siyam',
    storageBucket: 'inventory-app-siyam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbSfc8SRkHE6Q2HpNj4TNRh5eSFVlCr6k',
    appId: '1:985173152011:ios:85b22924b620a61125120e',
    messagingSenderId: '985173152011',
    projectId: 'inventory-app-siyam',
    storageBucket: 'inventory-app-siyam.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbSfc8SRkHE6Q2HpNj4TNRh5eSFVlCr6k',
    appId: '1:985173152011:ios:85b22924b620a61125120e',
    messagingSenderId: '985173152011',
    projectId: 'inventory-app-siyam',
    storageBucket: 'inventory-app-siyam.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGZ_JRCAidAZVsnsvRwQcNWwasGNYVAnA',
    appId: '1:985173152011:web:e0201e2f1e8df28825120e',
    messagingSenderId: '985173152011',
    projectId: 'inventory-app-siyam',
    authDomain: 'inventory-app-siyam.firebaseapp.com',
    storageBucket: 'inventory-app-siyam.firebasestorage.app',
    measurementId: 'G-WCF9CVJWW5',
  );
}
